-- Eksik modüller: Çek & Senet, Bakım Ücretleri, Araç Takip, Bildirimler,
-- Stok Lokasyonları, Belge Formları (Kurtarma/Eğitim), + quotes.type & users konum alanları.
-- Uygula: psql -d liftonom -f api-net/Migrations/2026_06_30_extra_modules.sql

-- Çek & Senet
CREATE TABLE IF NOT EXISTS checks (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id   bigint NOT NULL,
  customer_id bigint,
  type        text NOT NULL DEFAULT 'cek',
  direction   text NOT NULL DEFAULT 'received',
  amount      numeric(18,2) NOT NULL DEFAULT 0,
  bank        text,
  serial_no   text,
  due_date    date,
  status      text NOT NULL DEFAULT 'portfolio',
  notes       text,
  created_at  timestamptz NOT NULL DEFAULT now(),
  updated_at  timestamptz NOT NULL DEFAULT now(),
  deleted_at  timestamptz
);
CREATE INDEX IF NOT EXISTS ix_checks_tenant ON checks (tenant_id);

-- Bakım Ücretleri
CREATE TABLE IF NOT EXISTS maintenance_fees (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id   bigint NOT NULL,
  customer_id bigint,
  building_id bigint,
  amount      numeric(18,2) NOT NULL DEFAULT 0,
  period      text NOT NULL DEFAULT 'monthly',
  valid_from  date,
  notes       text,
  is_active   boolean NOT NULL DEFAULT true,
  created_at  timestamptz NOT NULL DEFAULT now(),
  updated_at  timestamptz NOT NULL DEFAULT now(),
  deleted_at  timestamptz
);
CREATE INDEX IF NOT EXISTS ix_maintenance_fees_tenant ON maintenance_fees (tenant_id);

-- Araç Takip
CREATE TABLE IF NOT EXISTS vehicles (
  id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id           bigint NOT NULL,
  plate               text NOT NULL DEFAULT '',
  brand               text,
  model               text,
  assigned_user_id    bigint,
  status              text NOT NULL DEFAULT 'active',
  last_lat            double precision,
  last_lng            double precision,
  location_updated_at timestamptz,
  notes               text,
  created_at          timestamptz NOT NULL DEFAULT now(),
  updated_at          timestamptz NOT NULL DEFAULT now(),
  deleted_at          timestamptz
);
CREATE INDEX IF NOT EXISTS ix_vehicles_tenant ON vehicles (tenant_id);

-- Bildirimler
CREATE TABLE IF NOT EXISTS notifications (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id   bigint NOT NULL,
  user_id     bigint,
  title       text NOT NULL DEFAULT '',
  body        text,
  type        text,
  link        text,
  is_read     boolean NOT NULL DEFAULT false,
  created_at  timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS ix_notifications_tenant ON notifications (tenant_id);

-- Stok Lokasyonları
CREATE TABLE IF NOT EXISTS stock_locations (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id   bigint NOT NULL,
  name        text NOT NULL DEFAULT '',
  code        text,
  description text,
  created_at  timestamptz NOT NULL DEFAULT now(),
  updated_at  timestamptz NOT NULL DEFAULT now(),
  deleted_at  timestamptz
);
CREATE INDEX IF NOT EXISTS ix_stock_locations_tenant ON stock_locations (tenant_id);

-- Belge Formları (Kurtarma / Eğitim)
CREATE TABLE IF NOT EXISTS document_forms (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id   bigint NOT NULL,
  kind        text NOT NULL DEFAULT 'rescue',
  customer_id bigint,
  building_id bigint,
  elevator_id bigint,
  title       text,
  form_data   jsonb DEFAULT '{}',
  status      text NOT NULL DEFAULT 'draft',
  created_by  bigint,
  created_at  timestamptz NOT NULL DEFAULT now(),
  updated_at  timestamptz NOT NULL DEFAULT now(),
  deleted_at  timestamptz
);
CREATE INDEX IF NOT EXISTS ix_document_forms_tenant ON document_forms (tenant_id, kind);

-- Revizyon teklifi: quotes.type
ALTER TABLE quotes ADD COLUMN IF NOT EXISTS type text NOT NULL DEFAULT 'standard';

-- Personel konum takibi: users konum alanları
ALTER TABLE users
  ADD COLUMN IF NOT EXISTS last_lat            double precision,
  ADD COLUMN IF NOT EXISTS last_lng            double precision,
  ADD COLUMN IF NOT EXISTS location_updated_at timestamptz;
