-- Cihaz push token'ları (FCM) — gerçek push bildirimi için.
-- Uygula: psql -d liftonom -f api-net/Migrations/2026_06_30_device_tokens.sql

CREATE TABLE IF NOT EXISTS device_tokens (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id  bigint NOT NULL,
  user_id    bigint NOT NULL,
  token      text NOT NULL,
  platform   text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX IF NOT EXISTS ux_device_tokens_token ON device_tokens (token);
CREATE INDEX IF NOT EXISTS ix_device_tokens_user ON device_tokens (tenant_id, user_id);
