using System.Text;
using System.Text.Json;
using Liftonom.Api.Data;
using Liftonom.Api.Middleware;
using Liftonom.Api.Services;
using Microsoft.AspNetCore.Authentication.JwtBearer;
using Microsoft.EntityFrameworkCore;
using Microsoft.IdentityModel.Tokens;

QuestPDF.Settings.License = QuestPDF.Infrastructure.LicenseType.Community;

var builder = WebApplication.CreateBuilder(args);

// JSON: tüm anahtarlar snake_case (Laravel/frontend ile uyumlu)
builder.Services.AddControllers().AddJsonOptions(o =>
{
    o.JsonSerializerOptions.PropertyNamingPolicy = JsonNamingPolicy.SnakeCaseLower;
    o.JsonSerializerOptions.DictionaryKeyPolicy = JsonNamingPolicy.SnakeCaseLower;
});

// EF Core + PostgreSQL + snake_case (mevcut tablolara eşlenir)
builder.Services.AddDbContext<AppDbContext>(opt =>
    opt.UseNpgsql(builder.Configuration.GetConnectionString("Default"))
       .UseSnakeCaseNamingConvention());

// Servisler
builder.Services.AddScoped<ITenantContext, TenantContext>();
builder.Services.AddScoped<OtpService>();
builder.Services.AddScoped<TokenService>();
builder.Services.AddScoped<LedgerService>();
builder.Services.AddScoped<ScheduledJobs>();
builder.Services.AddScoped<PdfService>();
builder.Services.AddScoped<ISmsSender, LogSmsSender>();
builder.Services.AddScoped<IEmailSender, SmtpEmailSender>();
builder.Services.AddScoped<FaultNotificationService>();
builder.Services.AddScoped<PushService>();
builder.Services.AddHttpClient();
// Ödeme: iyzico anahtarı varsa iyzico, yoksa mock
if (!string.IsNullOrEmpty(builder.Configuration["Iyzico:ApiKey"]))
    builder.Services.AddScoped<IPaymentGateway, IyzicoPaymentGateway>();
else
    builder.Services.AddScoped<IPaymentGateway, MockPaymentGateway>();
// WhatsApp: token varsa Meta Cloud API, yoksa log sürücüsü
if (!string.IsNullOrEmpty(builder.Configuration["WhatsApp:Token"]))
    builder.Services.AddScoped<IWhatsAppSender, MetaWhatsAppSender>();
else
    builder.Services.AddScoped<IWhatsAppSender, LogWhatsAppSender>();
builder.Services.AddHostedService<DailyJobsHostedService>();

// JWT
builder.Services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme)
    .AddJwtBearer(o =>
    {
        o.MapInboundClaims = false; // 'tid','uid' claim adlarını koru (URI'ye eşleme)
        o.TokenValidationParameters = new TokenValidationParameters
        {
            ValidateIssuer = true,
            ValidateAudience = true,
            ValidateLifetime = true,
            ValidateIssuerSigningKey = true,
            ValidIssuer = "Liftonom",
            ValidAudience = "Liftonom",
            IssuerSigningKey = new SymmetricSecurityKey(
                Encoding.UTF8.GetBytes(TokenService.JwtKey(builder.Configuration))),
        };
    });
builder.Services.AddAuthorizationBuilder()
    .AddPolicy("Admin", p => p.RequireClaim("scope", "admin"));

// CORS — geliştirmede tüm origin'lere izin (Next.js farklı port)
builder.Services.AddCors(o => o.AddDefaultPolicy(p =>
    p.AllowAnyOrigin().AllowAnyHeader().AllowAnyMethod()));

var app = builder.Build();

// Veritabanı hazırlığı + varsayılan süper admin (idempotent).
// Taze/boş DB'de EF modeli tam şema kaynağıdır → EnsureCreated tüm tabloları kurar
// (tablolar zaten varsa hiçbir şey yapmaz). RAW SQL migration'lar yalnız eski DB'yi evriltir.
using (var scope = app.Services.CreateScope())
{
    var db = scope.ServiceProvider.GetRequiredService<Liftonom.Api.Data.AppDbContext>();
    var startupLog = scope.ServiceProvider.GetRequiredService<ILoggerFactory>().CreateLogger("Startup");

    // Postgres konteyneri API'den sonra hazır olabilir — kısa yeniden deneme döngüsü.
    for (var attempt = 1; ; attempt++)
    {
        try { await db.Database.EnsureCreatedAsync(); break; }
        catch (Exception ex) when (attempt < 12)
        {
            startupLog.LogWarning("DB hazır değil (deneme {Attempt}/12): {Message}", attempt, ex.Message);
            await Task.Delay(TimeSpan.FromSeconds(3));
        }
    }

    // Süper Admin ek tabloları — mevcut DB'de EnsureCreated eklemez, idempotent oluştur.
    await db.Database.ExecuteSqlRawAsync("""
        CREATE TABLE IF NOT EXISTS subscription_contracts (
          id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          tenant_id bigint NOT NULL,
          title text NOT NULL DEFAULT '',
          plan text,
          amount numeric(18,2) NOT NULL DEFAULT 0,
          currency text NOT NULL DEFAULT 'TRY',
          start_date date,
          end_date date,
          status text NOT NULL DEFAULT 'active',
          notes text,
          created_at timestamptz NOT NULL DEFAULT now(),
          updated_at timestamptz NOT NULL DEFAULT now(),
          deleted_at timestamptz
        );
        CREATE INDEX IF NOT EXISTS ix_subscription_contracts_tenant ON subscription_contracts (tenant_id);
        CREATE TABLE IF NOT EXISTS platform_settings (
          id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          platform_name text,
          support_email text,
          default_plan text,
          created_at timestamptz NOT NULL DEFAULT now(),
          updated_at timestamptz NOT NULL DEFAULT now()
        );
        CREATE TABLE IF NOT EXISTS landing_items (
          id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          section text NOT NULL DEFAULT 'feature',
          title text NOT NULL DEFAULT '',
          description text,
          icon text,
          sort_order int NOT NULL DEFAULT 0,
          is_active boolean NOT NULL DEFAULT true,
          created_at timestamptz NOT NULL DEFAULT now(),
          updated_at timestamptz NOT NULL DEFAULT now()
        );
        CREATE TABLE IF NOT EXISTS landing_settings (
          id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          hero_badge text,
          hero_title text,
          hero_title_accent text,
          hero_subtitle text,
          show_pricing boolean NOT NULL DEFAULT true,
          created_at timestamptz NOT NULL DEFAULT now(),
          updated_at timestamptz NOT NULL DEFAULT now()
        );
        CREATE TABLE IF NOT EXISTS content_pages (
          id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          type text NOT NULL DEFAULT 'blog',
          slug text NOT NULL DEFAULT '',
          title text NOT NULL DEFAULT '',
          excerpt text,
          body text,
          cover_url text,
          icon text,
          sort_order int NOT NULL DEFAULT 0,
          is_published boolean NOT NULL DEFAULT true,
          published_at date,
          created_at timestamptz NOT NULL DEFAULT now(),
          updated_at timestamptz NOT NULL DEFAULT now(),
          deleted_at timestamptz
        );
        CREATE INDEX IF NOT EXISTS ix_content_pages_type ON content_pages (type);
        CREATE INDEX IF NOT EXISTS ix_content_pages_slug ON content_pages (slug);
        CREATE TABLE IF NOT EXISTS whatsapp_templates (
          id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          tenant_id bigint NOT NULL,
          name text NOT NULL DEFAULT '',
          body text NOT NULL DEFAULT '',
          created_at timestamptz NOT NULL DEFAULT now(),
          updated_at timestamptz NOT NULL DEFAULT now(),
          deleted_at timestamptz
        );
        CREATE INDEX IF NOT EXISTS ix_whatsapp_templates_tenant ON whatsapp_templates (tenant_id);
        CREATE TABLE IF NOT EXISTS product_categories (
          id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          tenant_id bigint NOT NULL,
          name text NOT NULL DEFAULT '',
          created_at timestamptz NOT NULL DEFAULT now(),
          updated_at timestamptz NOT NULL DEFAULT now(),
          deleted_at timestamptz
        );
        CREATE INDEX IF NOT EXISTS ix_product_categories_tenant ON product_categories (tenant_id);

        -- Müşteri yetkili kişi alanı (mevcut/eski DB için idempotent)
        ALTER TABLE customers ADD COLUMN IF NOT EXISTS authorized_person text;
        -- Hızlı kurulum ek alanları (bina tipi/daire, asansör durak, ücret bitiş)
        ALTER TABLE buildings ADD COLUMN IF NOT EXISTS type text;
        ALTER TABLE buildings ADD COLUMN IF NOT EXISTS unit_count integer;
        ALTER TABLE elevators ADD COLUMN IF NOT EXISTS stop_count integer;
        ALTER TABLE maintenance_fees ADD COLUMN IF NOT EXISTS valid_to date;
        -- Bina detay alanları (yeni bina formu)
        ALTER TABLE buildings ADD COLUMN IF NOT EXISTS postal_code text;
        ALTER TABLE buildings ADD COLUMN IF NOT EXISTS phone text;
        ALTER TABLE buildings ADD COLUMN IF NOT EXISTS email text;
        ALTER TABLE buildings ADD COLUMN IF NOT EXISTS built_year integer;
        ALTER TABLE buildings ADD COLUMN IF NOT EXISTS manager_email text;
        ALTER TABLE buildings ADD COLUMN IF NOT EXISTS default_technician_user_id bigint;
        ALTER TABLE buildings ADD COLUMN IF NOT EXISTS is_active boolean NOT NULL DEFAULT true;
        ALTER TABLE buildings ADD COLUMN IF NOT EXISTS door_code text;
        ALTER TABLE buildings ADD COLUMN IF NOT EXISTS access_note text;
        -- Asansör detay alanları (yeni asansör formu)
        ALTER TABLE elevators ADD COLUMN IF NOT EXISTS capacity_persons integer;
        ALTER TABLE elevators ADD COLUMN IF NOT EXISTS served_floors text;
        ALTER TABLE elevators ADD COLUMN IF NOT EXISTS speed_ms numeric;
        ALTER TABLE elevators ADD COLUMN IF NOT EXISTS door_type text;
        ALTER TABLE elevators ADD COLUMN IF NOT EXISTS registration_no text;
        ALTER TABLE elevators ADD COLUMN IF NOT EXISTS manufacture_year integer;
        ALTER TABLE elevators ADD COLUMN IF NOT EXISTS installation_date date;
        ALTER TABLE elevators ADD COLUMN IF NOT EXISTS tse_label_color text;
        ALTER TABLE elevators ADD COLUMN IF NOT EXISTS tse_label_note text;
        ALTER TABLE elevators ADD COLUMN IF NOT EXISTS has_emergency_phone boolean NOT NULL DEFAULT false;
        ALTER TABLE elevators ADD COLUMN IF NOT EXISTS has_ups boolean NOT NULL DEFAULT false;
        ALTER TABLE elevators ADD COLUMN IF NOT EXISTS has_fire_system boolean NOT NULL DEFAULT false;
        ALTER TABLE elevators ADD COLUMN IF NOT EXISTS has_earthquake_sensor boolean NOT NULL DEFAULT false;
        -- Bölge sorumlu personel
        ALTER TABLE regions ADD COLUMN IF NOT EXISTS responsible_user_id bigint;
        -- Bakım kaydı ek alanları
        ALTER TABLE maintenance_records ADD COLUMN IF NOT EXISTS is_critical boolean NOT NULL DEFAULT false;
        ALTER TABLE maintenance_records ADD COLUMN IF NOT EXISTS description text;
        ALTER TABLE maintenance_records ADD COLUMN IF NOT EXISTS notes text;
        -- Arıza bildirimi ek alanları
        ALTER TABLE fault_reports ADD COLUMN IF NOT EXISTS title text;
        ALTER TABLE fault_reports ADD COLUMN IF NOT EXISTS type text;
        ALTER TABLE fault_reports ADD COLUMN IF NOT EXISTS code text;
        ALTER TABLE fault_reports ADD COLUMN IF NOT EXISTS contact_name text;
        ALTER TABLE fault_reports ADD COLUMN IF NOT EXISTS contact_phone text;
        ALTER TABLE fault_reports ADD COLUMN IF NOT EXISTS symptoms text;
        ALTER TABLE fault_reports ADD COLUMN IF NOT EXISTS work_done text;
        ALTER TABLE fault_reports ADD COLUMN IF NOT EXISTS under_warranty boolean NOT NULL DEFAULT false;
        ALTER TABLE fault_reports ADD COLUMN IF NOT EXISTS billable boolean NOT NULL DEFAULT true;
        ALTER TABLE fault_reports ADD COLUMN IF NOT EXISTS notes text;
        -- Asansör siparişi ek alanları
        ALTER TABLE elevator_orders ADD COLUMN IF NOT EXISTS building_id bigint;
        ALTER TABLE elevator_orders ADD COLUMN IF NOT EXISTS project_name text;
        ALTER TABLE elevator_orders ADD COLUMN IF NOT EXISTS capacity_kg integer;
        ALTER TABLE elevator_orders ADD COLUMN IF NOT EXISTS capacity_persons integer;
        ALTER TABLE elevator_orders ADD COLUMN IF NOT EXISTS floor_count integer;
        ALTER TABLE elevator_orders ADD COLUMN IF NOT EXISTS stop_count integer;
        ALTER TABLE elevator_orders ADD COLUMN IF NOT EXISTS speed_ms numeric;
        ALTER TABLE elevator_orders ADD COLUMN IF NOT EXISTS door_type text;
        ALTER TABLE elevator_orders ADD COLUMN IF NOT EXISTS order_date date;
        ALTER TABLE elevator_orders ADD COLUMN IF NOT EXISTS estimated_end date;
        ALTER TABLE elevator_orders ADD COLUMN IF NOT EXISTS downpayment numeric;
        ALTER TABLE elevator_orders ADD COLUMN IF NOT EXISTS technical_details text;
        -- Sözleşme belge sistemi: şablonlar + sözleşme ek alanları
        CREATE TABLE IF NOT EXISTS contract_templates (
            id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            tenant_id bigint NOT NULL,
            name text NOT NULL,
            type text NOT NULL DEFAULT 'Bakım Sözleşmesi',
            is_default boolean NOT NULL DEFAULT false,
            is_active boolean NOT NULL DEFAULT true,
            clauses jsonb NOT NULL DEFAULT '[]',
            variables jsonb NOT NULL DEFAULT '[]',
            created_at timestamptz NOT NULL DEFAULT now(),
            updated_at timestamptz NOT NULL DEFAULT now(),
            deleted_at timestamptz
        );
        CREATE INDEX IF NOT EXISTS ix_contract_templates_tenant ON contract_templates (tenant_id);
        ALTER TABLE contracts ADD COLUMN IF NOT EXISTS building_id bigint;
        ALTER TABLE contracts ADD COLUMN IF NOT EXISTS template_id bigint;
        ALTER TABLE contracts ADD COLUMN IF NOT EXISTS currency text NOT NULL DEFAULT 'TRY';
        ALTER TABLE contracts ADD COLUMN IF NOT EXISTS period text;
        ALTER TABLE contracts ADD COLUMN IF NOT EXISTS annual_visits integer;
        ALTER TABLE contracts ADD COLUMN IF NOT EXISTS renewal_notice_days integer NOT NULL DEFAULT 30;
        ALTER TABLE contracts ADD COLUMN IF NOT EXISTS document_status text NOT NULL DEFAULT 'draft';
        ALTER TABLE contracts ADD COLUMN IF NOT EXISTS customer_name text;
        ALTER TABLE contracts ADD COLUMN IF NOT EXISTS rep_name text;
        ALTER TABLE contracts ADD COLUMN IF NOT EXISTS phone text;
        ALTER TABLE contracts ADD COLUMN IF NOT EXISTS email text;
        ALTER TABLE contracts ADD COLUMN IF NOT EXISTS terms text;
        ALTER TABLE contracts ADD COLUMN IF NOT EXISTS clauses jsonb NOT NULL DEFAULT '[]';
        ALTER TABLE contracts ADD COLUMN IF NOT EXISTS public_token text;
        ALTER TABLE contracts ADD COLUMN IF NOT EXISTS company_signature text;
        ALTER TABLE contracts ADD COLUMN IF NOT EXISTS customer_signature text;
        ALTER TABLE contracts ADD COLUMN IF NOT EXISTS sent_at timestamptz;
        ALTER TABLE contracts ADD COLUMN IF NOT EXISTS approved_at timestamptz;
        ALTER TABLE tenants ADD COLUMN IF NOT EXISTS contract_email_subject text;
        ALTER TABLE tenants ADD COLUMN IF NOT EXISTS contract_email_body text;
        ALTER TABLE platform_settings ADD COLUMN IF NOT EXISTS smtp_host text;
        ALTER TABLE platform_settings ADD COLUMN IF NOT EXISTS smtp_port integer;
        ALTER TABLE platform_settings ADD COLUMN IF NOT EXISTS smtp_user text;
        ALTER TABLE platform_settings ADD COLUMN IF NOT EXISTS smtp_password text;
        ALTER TABLE platform_settings ADD COLUMN IF NOT EXISTS smtp_from text;
        ALTER TABLE platform_settings ADD COLUMN IF NOT EXISTS smtp_from_name text;
        ALTER TABLE platform_settings ADD COLUMN IF NOT EXISTS smtp_ssl boolean NOT NULL DEFAULT true;
        -- Teklif belge sistemi: şablonlar + teklif ek alanları
        CREATE TABLE IF NOT EXISTS quote_templates (
            id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            tenant_id bigint NOT NULL,
            name text NOT NULL,
            type text NOT NULL DEFAULT 'Teklif',
            is_default boolean NOT NULL DEFAULT false,
            is_active boolean NOT NULL DEFAULT true,
            clauses jsonb NOT NULL DEFAULT '[]',
            variables jsonb NOT NULL DEFAULT '[]',
            created_at timestamptz NOT NULL DEFAULT now(),
            updated_at timestamptz NOT NULL DEFAULT now(),
            deleted_at timestamptz
        );
        CREATE INDEX IF NOT EXISTS ix_quote_templates_tenant ON quote_templates (tenant_id);
        ALTER TABLE quotes ADD COLUMN IF NOT EXISTS template_id bigint;
        ALTER TABLE quotes ADD COLUMN IF NOT EXISTS document_status text NOT NULL DEFAULT 'draft';
        ALTER TABLE quotes ADD COLUMN IF NOT EXISTS title text;
        ALTER TABLE quotes ADD COLUMN IF NOT EXISTS customer_name text;
        ALTER TABLE quotes ADD COLUMN IF NOT EXISTS email text;
        ALTER TABLE quotes ADD COLUMN IF NOT EXISTS phone text;
        ALTER TABLE quotes ADD COLUMN IF NOT EXISTS currency text NOT NULL DEFAULT 'TRY';
        ALTER TABLE quotes ADD COLUMN IF NOT EXISTS terms text;
        ALTER TABLE quotes ADD COLUMN IF NOT EXISTS public_token text;
        ALTER TABLE quotes ADD COLUMN IF NOT EXISTS sent_at timestamptz;
        ALTER TABLE quotes ADD COLUMN IF NOT EXISTS elevator_id bigint;
        ALTER TABLE quotes ADD COLUMN IF NOT EXISTS contact_name text;
        ALTER TABLE quotes ADD COLUMN IF NOT EXISTS address text;
        ALTER TABLE quotes ADD COLUMN IF NOT EXISTS labor_total numeric;
        ALTER TABLE quotes ADD COLUMN IF NOT EXISTS material_total numeric;
        ALTER TABLE quotes ADD COLUMN IF NOT EXISTS price_visible boolean NOT NULL DEFAULT true;
        ALTER TABLE quotes ADD COLUMN IF NOT EXISTS internal_notes text;
        ALTER TABLE quotes ADD COLUMN IF NOT EXISTS company_signature text;
        ALTER TABLE quotes ADD COLUMN IF NOT EXISTS customer_signature text;
        ALTER TABLE quote_templates ADD COLUMN IF NOT EXISTS kind text NOT NULL DEFAULT 'standard';
        ALTER TABLE quotes ADD COLUMN IF NOT EXISTS inspector_name text;
        ALTER TABLE quotes ADD COLUMN IF NOT EXISTS defects jsonb NOT NULL DEFAULT '[]';
        ALTER TABLE quotes ADD COLUMN IF NOT EXISTS actions jsonb NOT NULL DEFAULT '[]';
        ALTER TABLE quotes ADD COLUMN IF NOT EXISTS elevator_type text;
        ALTER TABLE quotes ADD COLUMN IF NOT EXISTS elevator_count integer;
        ALTER TABLE quotes ADD COLUMN IF NOT EXISTS capacity_kg integer;
        ALTER TABLE quotes ADD COLUMN IF NOT EXISTS capacity_persons integer;
        ALTER TABLE quotes ADD COLUMN IF NOT EXISTS floor_count integer;
        ALTER TABLE quotes ADD COLUMN IF NOT EXISTS stop_count integer;
        ALTER TABLE quotes ADD COLUMN IF NOT EXISTS speed_ms numeric;
        ALTER TABLE quotes ADD COLUMN IF NOT EXISTS door_type text;
        ALTER TABLE quotes ADD COLUMN IF NOT EXISTS control_system text;
        ALTER TABLE quotes ADD COLUMN IF NOT EXISTS unit_price numeric;
        ALTER TABLE quotes ADD COLUMN IF NOT EXISTS warranty_years integer;
        ALTER TABLE quotes ADD COLUMN IF NOT EXISTS delivery_days integer;
        ALTER TABLE quotes ADD COLUMN IF NOT EXISTS payment_terms text;
        """);

    if (!await db.PlatformSettings.AnyAsync())
    {
        db.PlatformSettings.Add(new Liftonom.Api.Models.PlatformSetting
        {
            PlatformName = "Liftonom", SupportEmail = "info@liftonom.com", DefaultPlan = "trial",
            CreatedAt = DateTime.UtcNow, UpdatedAt = DateTime.UtcNow,
        });
        await db.SaveChangesAsync();
    }

    // Landing içeriği (tanıtım sayfası) — varsayılan içerik, süper adminden düzenlenir.
    if (!await db.LandingSettings.AnyAsync())
    {
        db.LandingSettings.Add(new Liftonom.Api.Models.LandingSetting
        {
            HeroBadge = "Asansör bakım & servis yönetim platformu",
            HeroTitle = "Asansör operasyonunuzu",
            HeroTitleAccent = "tek panelden",
            HeroSubtitle = "Bakım, arıza, muayene, stok, finans ve saha ekibi — hepsi Liftonom'da. Ofis paneli ve teknisyen mobil uygulamasıyla sahayı gerçek zamanlı takip edin.",
            ShowPricing = true, CreatedAt = DateTime.UtcNow, UpdatedAt = DateTime.UtcNow,
        });
        await db.SaveChangesAsync();
    }
    if (!await db.LandingItems.AnyAsync())
    {
        var lnow = DateTime.UtcNow;
        var order = 0;
        void Add(string section, string title, string? desc, string? icon)
            => db.LandingItems.Add(new Liftonom.Api.Models.LandingItem
            {
                Section = section, Title = title, Description = desc, Icon = icon,
                SortOrder = order++, IsActive = true, CreatedAt = lnow, UpdatedAt = lnow,
            });

        order = 0;
        Add("feature", "Akıllı Bakım Takvimi", "Periyodik bakımlar otomatik planlanır; 30/15/7/1 gün önce hatırlatma. Hiçbir bakım atlanmaz.", "CalendarClock");
        Add("feature", "6 Aşamalı Arıza Yönetimi", "Bildirim → sevk → inceleme → onarım → parça → tamamlandı. Her aşama zaman damgalı, teknisyen konumuyla.", "Wrench");
        Add("feature", "Offline Mobil Çalışma", "Makine dairesi, sinyalsiz bölge — internet olmadan bakım tamamlanır, bağlantı gelince senkronlanır.", "WifiOff");
        Add("feature", "QR ile Sıfır Temaslı Arıza", "Müşteri kabindeki QR'ı okutur, uygulama indirmeden arıza bildirir; size anında bildirim düşer.", "QrCode");
        Add("feature", "TSE A/B/C/D Dijital Form", "Mevzuata uygun periyodik kontrol formları mobilde doldurulur, müşteri imzalar, bulutta arşivlenir.", "ShieldCheck");
        Add("feature", "Sahada Mobil Tahsilat", "Teknisyen nakit/kart/online link ile anında tahsilat alır; dijital makbuz oluşur.", "Wallet");

        order = 0;
        Add("module", "Bakım Takip", "Periyodik bakımları planla, ata; dijital servis formu + fotoğraf + imzayla raporla.", "CalendarClock");
        Add("module", "Arıza Yönetimi", "Arızalar tek panele düşer, en yakın teknisyene atanır, SLA ölçülür.", "Wrench");
        Add("module", "Teknisyen Mobil", "iOS + Android native uygulama. Sahada görev al, tamamla, offline çalış.", "Smartphone");
        Add("module", "Fatura & Tahsilat", "Bakım kapanışında tek tıkla fatura; online ödeme linki ve vade takibi.", "Receipt");
        Add("module", "Stok & Depo", "Ürün, kategori, lokasyon, tedarikçi + düşük stok uyarıları.", "Boxes");
        Add("module", "Müşteri Portalı", "Bina yöneticisi binalarını, bakımlarını ve arızalarını görür.", "Users");

        order = 0;
        Add("step", "60 Saniyede Kayıt", "E-posta ile firmanı oluştur; hesabın anında aktif. Kredi kartı gerekmez.", "UserPlus");
        Add("step", "Verilerini Aktar", "Mevcut Excel verilerini toplu yükle. Ekibimiz transfer desteği sunar.", "Upload");
        Add("step", "Ekibini Davet Et", "Teknisyen, ofis, finans — herkesi rolüne göre ekle. Saha hazır.", "Users");
        Add("step", "Dijital Operasyona Geç", "Bakım, arıza, fatura, sözleşme tek panelde. Şeffaflık müşteri portalıyla.", "Rocket");

        order = 0;
        Add("compare_old", "Periyodik bakım takvimi unutulur, ceza riski doğar", null, null);
        Add("compare_old", "Teknisyen sahada ne yaptı akşama kadar belirsiz", null, null);
        Add("compare_old", "Servis formları kağıtta; denetimde belge bulunamaz", null, null);
        Add("compare_old", "Fatura kesimi sarkar, tahsilat geç kalır", null, null);
        Add("compare_old", "Müşteri 'bakım ne zamandı?' diye sürekli arar", null, null);

        order = 0;
        Add("compare_new", "Bakım takvimi otomatik; 30/15/7/1 gün önce hatırlatma", null, null);
        Add("compare_new", "Saha durumu canlı; konum, fotoğraf ve imza anında ofiste", null, null);
        Add("compare_new", "Dijital form bulutta; denetimde 30 saniyede belge", null, null);
        Add("compare_new", "Bakım kapanırken tek tıkla fatura + online ödeme linki", null, null);
        Add("compare_new", "Müşteri portalı + QR ile bilgi müşterinin elinde", null, null);

        await db.SaveChangesAsync();
    }

    // Müşteri yorumları + SSS — bölüm bazlı idempotent seed (mevcut DB'ye de eklensin diye ayrı).
    if (!await db.LandingItems.AnyAsync(i => i.Section == "testimonial"))
    {
        var tnow = DateTime.UtcNow;
        var to = 0;
        void AddT(string who, string quote) => db.LandingItems.Add(new Liftonom.Api.Models.LandingItem
        { Section = "testimonial", Title = who, Description = quote, SortOrder = to++, IsActive = true, CreatedAt = tnow, UpdatedAt = tnow });
        AddT("Mehmet Demir — Demir Asansör", "Bakım takvimini artık hiç kaçırmıyoruz. Teknisyenlerin sahadaki durumunu anlık görmek işimizi kökten değiştirdi.");
        AddT("Ayşe Kaya — Kaya Lift", "Kağıt formlardan kurtulduk; TSE denetiminde tüm belgeler saniyeler içinde elimizde. Tahsilat da hızlandı.");
        AddT("Kürşad Özhamam — Öz Asansör", "Tek panelden bakım, arıza ve faturayı yönetmek harika. Ekip verimliliğimiz belirgin arttı.");
        await db.SaveChangesAsync();
    }
    if (!await db.LandingItems.AnyAsync(i => i.Section == "faq"))
    {
        var fnow = DateTime.UtcNow;
        var fo = 0;
        void AddF(string q, string a) => db.LandingItems.Add(new Liftonom.Api.Models.LandingItem
        { Section = "faq", Title = q, Description = a, SortOrder = fo++, IsActive = true, CreatedAt = fnow, UpdatedAt = fnow });
        AddF("Kurulum ve eğitim ücretli mi?", "Hayır. Kurulum, veri aktarımı ve ekip eğitimi abonelik fiyatına dahildir.");
        AddF("Mevcut Excel verilerimi aktarabilir miyim?", "Evet. Şablona dönüştürüp toplu yükleyebilirsiniz; ekibimiz transfer desteği sunar.");
        AddF("Teknisyen uygulaması internetsiz çalışır mı?", "Evet. Sinyalsiz bölgede bakım tamamlanır, imza alınır; bağlantı gelince otomatik senkronlanır.");
        AddF("İstediğim zaman iptal edebilir miyim?", "Aylık abonelikte taahhüt yoktur, dilediğiniz zaman iptal edebilirsiniz. Yıllık abonelik daha avantajlıdır.");
        AddF("Verilerim güvende mi?", "Her firmanın verisi izole tutulur (çok kiracılı mimari), düzenli yedeklenir ve şifreli saklanır.");
        await db.SaveChangesAsync();
    }

    // Varsayılan planlar (landing fiyatlandırma + admin Planlar modülü için)
    if (!await db.Plans.AnyAsync())
    {
        var pnow = DateTime.UtcNow;
        db.Plans.AddRange(
            new Liftonom.Api.Models.Plan { Code = "baslangic", Name = "Başlangıç", MonthlyPrice = 1500m, MaxUsers = 10, MaxElevators = 500, IsActive = true, CreatedAt = pnow, UpdatedAt = pnow },
            new Liftonom.Api.Models.Plan { Code = "pro", Name = "Professional", MonthlyPrice = 2500m, MaxUsers = 25, MaxElevators = 1000, IsActive = true, CreatedAt = pnow, UpdatedAt = pnow },
            new Liftonom.Api.Models.Plan { Code = "kurumsal", Name = "Kurumsal", MonthlyPrice = 3500m, MaxUsers = null, MaxElevators = 2000, IsActive = true, CreatedAt = pnow, UpdatedAt = pnow }
        );
        await db.SaveChangesAsync();
    }

    // İçerik sayfaları — çözüm/şehir/blog/yasal (bölüm bazlı idempotent seed).
    {
        var cnow = DateTime.UtcNow;
        var today = DateOnly.FromDateTime(cnow);
        void AddC(string type, int order, string slug, string title, string excerpt, string body, string? icon)
            => db.ContentPages.Add(new Liftonom.Api.Models.ContentPage
            {
                Type = type, Slug = slug, Title = title, Excerpt = excerpt, Body = body, Icon = icon,
                SortOrder = order, IsPublished = true, PublishedAt = today, CreatedAt = cnow, UpdatedAt = cnow,
            });

        if (!await db.ContentPages.AnyAsync(c => c.Type == "solution"))
        {
            AddC("solution", 0, "bakim-takip", "Asansör Bakım Takip", "Periyodik bakımları otomatik planlayın, teknisyene atayın, dijital formla raporlayın.",
                "Asansör Bakım Takip modülü, periyodik bakımlarınızı sözleşme süresince otomatik takvime dizer ve 30/15/7/1 gün öncesinden hatırlatır.\n\nTeknisyen sahada bakımı tamamlayınca dijital servis formu, fotoğraf ve müşteri imzasıyla anında raporlanır. A/B/C/D tipi periyodik kontrol formları sistemde hazırdır; denetimde tüm belgeler saniyeler içinde elinizin altında olur.", "CalendarClock");
            AddC("solution", 1, "ariza-yonetimi", "Arıza Yönetimi", "Arızalar tek panele düşer, en yakın teknisyene atanır, süre (SLA) ölçülür.",
                "Müşteriden gelen arıza bildirimleri tek panele düşer ve konum bazlı en uygun teknisyene atanır. Bildirim → sevk → inceleme → onarım → parça → tamamlandı olmak üzere 6 aşamalı yaşam döngüsüyle her adım zaman damgalı izlenir.\n\nMüşteriye anlık durum bilgisi iletilir; müdahale süresi (SLA) raporlanır. Böylece hem şeffaflık hem de ölçülebilir performans elde edersiniz.", "Wrench");
            AddC("solution", 2, "teknisyen-mobil", "Teknisyen Mobil Uygulaması", "iOS + Android native uygulama; sahada görev al, tamamla, offline çalış.",
                "Saha ekibiniz iOS ve Android native uygulamayla kendisine atanan bakım ve arızaları görür, tamamlar, fotoğraf ve imza ekler.\n\nUygulama offline çalışır: makine dairesi veya sinyalsiz bölgede bakım tamamlanır, bağlantı gelince otomatik senkronlanır. Aktif görev varken pil dostu canlı konum paylaşımı sayesinde ofis, sahayı gerçek zamanlı izler.", "Smartphone");
            AddC("solution", 3, "fatura-tahsilat", "Fatura & Tahsilat", "Bakım kapanışında tek tıkla fatura; online ödeme linki ve vade takibi.",
                "Bakım veya iş kapanışında tek tıkla fatura oluşturun. E-posta ve online ödeme linkiyle tahsilatı hızlandırın; cari hesap, kasa, çek-senet ve finansal özet tek yerde.\n\nVade takibi ve tahsilat raporlarıyla nakit akışınızı anlık görürsünüz.", "Receipt");
            AddC("solution", 4, "stok-depo", "Stok & Depo", "Ürün, kategori, lokasyon ve tedarikçi yönetimi + düşük stok uyarıları.",
                "Yedek parça ve sarf malzemelerinizi ürün, kategori, lokasyon ve tedarikçi bazında yönetin. Stok hareketleri kayıt altında; düşük stok uyarılarıyla parça hiç bitmez.\n\nHangi parçanın nerede olduğunu ve hangi işte kullanıldığını anında görürsünüz.", "Boxes");
            AddC("solution", 5, "musteri-portali", "Müşteri Portalı", "Bina/apartman yöneticisi bakım ve arızalarını şeffaflıkla takip eder.",
                "Bina ve apartman yöneticileri kendi binalarının bakım geçmişini, yaklaşan bakımları ve açık arızaları müşteri portalından görür. QR kod ile bilgi her zaman müşterinin elinin altındadır.\n\nBu şeffaflık, müşteri memnuniyetini ve sözleşme yenileme oranını artırır.", "Users");
            await db.SaveChangesAsync();
        }

        if (!await db.ContentPages.AnyAsync(c => c.Type == "city"))
        {
            void AddCity(int o, string slug, string il) => AddC("city", o, slug, $"{il} Asansör Bakım Yazılımı",
                $"{il}'da asansör bakım ve servis firmaları için bulut tabanlı operasyon yönetimi.",
                $"{il} genelinde faaliyet gösteren asansör bakım firmaları, Liftonom ile periyodik bakım, arıza, muayene, stok ve finans süreçlerini tek panelden yönetir.\n\nSaha teknisyenleri {il} içindeki tüm servis noktalarına mobil uygulamayla atanır; bakımlar dijital formla raporlanır, faturalar tek tıkla kesilir. Kağıt ve Excel'e gerek kalmadan, {il}'daki tüm asansör operasyonunuz dijitalleşir.", null);
            AddCity(0, "istanbul", "İstanbul");
            AddCity(1, "ankara", "Ankara");
            AddCity(2, "izmir", "İzmir");
            AddCity(3, "bursa", "Bursa");
            await db.SaveChangesAsync();
        }

        if (!await db.ContentPages.AnyAsync(c => c.Type == "blog"))
        {
            AddC("blog", 0, "periyodik-asansor-bakimi-neden-onemli", "Periyodik Asansör Bakımı Neden Önemli?",
                "Periyodik bakımın yasal, güvenlik ve maliyet boyutlarını ve dijital takibin faydalarını ele alıyoruz.",
                "Asansörler, düzenli bakım gerektiren güvenlik kritik sistemlerdir. Periyodik bakım hem yasal bir zorunluluk hem de kullanıcı güvenliğinin temelidir.\n\nBakımların aksaması; kaza riski, yasal ceza ve beklenmedik arıza maliyeti demektir. Dijital bir takip sistemi, bakım takvimini otomatik kurar, hatırlatır ve her bakımı belgeleyerek bu riskleri ortadan kaldırır.\n\nLiftonom ile periyodik bakımlarınız asla atlanmaz; denetimlerde tüm kayıtlar saniyeler içinde hazırdır.", null);
            AddC("blog", 1, "tse-a-b-c-d-muayene-formlari", "TSE A/B/C/D Periyodik Kontrol Formları Rehberi",
                "A, B, C, D tipi periyodik kontrol formlarının farkları ve dijital doldurmanın avantajları.",
                "Asansör periyodik kontrolleri, kusur derecesine göre A/B/C/D olarak sınıflandırılır. Her tip, farklı aciliyet ve işlem gerektirir.\n\nBu formların kağıt üzerinde tutulması; kaybolma, eksik doldurma ve denetimde belge bulamama riskleri taşır. Dijital form ile teknisyen mobilde doldurur, müşteri imzalar, belge bulutta 10+ yıl arşivlenir.\n\nBöylece mevzuata tam uyum sağlar, denetim süreçlerini kolaylaştırırsınız.", null);
            AddC("blog", 2, "asansor-firmalari-icin-dijital-donusum", "Asansör Firmaları İçin Dijital Dönüşüm",
                "Excel ve WhatsApp'tan tek panele geçiş; verimlilik ve karlılık üzerindeki etkisi.",
                "Birçok asansör firması operasyonunu hâlâ Excel, WhatsApp ve kağıt formlarla yürütür. Bu dağınık yapı; unutulan bakımlar, geç tahsilat ve belirsiz saha durumu yaratır.\n\nTek panelde toplanan bir sistem; otomatik takvim, canlı saha takibi, dijital form ve tek tıkla fatura ile aynı işi çok daha az emekle yapar. Dijital dönüşüm, asansör firmaları için bir lüks değil rekabet gerekliliğidir.", null);
            await db.SaveChangesAsync();
        }

        if (!await db.ContentPages.AnyAsync(c => c.Type == "legal"))
        {
            const string note = "\n\n[Not: Bu metin bir taslaktır. Firma bilgilerinizle güncelleyin ve yayınlamadan önce hukuki inceleme yaptırın.]";
            AddC("legal", 0, "mesafeli-satis-sozlesmesi", "Mesafeli Satış Sözleşmesi",
                "Abonelik hizmet satışına ilişkin mesafeli satış sözleşmesi.",
                "1. TARAFLAR\nSatıcı: [Firma Adı], [Adres], [Vergi Dairesi/No]. Alıcı: hizmeti satın alan kullanıcı.\n\n2. KONU\nİşbu sözleşme, Alıcı'nın Liftonom yazılım aboneliği hizmetini elektronik ortamda satın almasına ilişkin hak ve yükümlülükleri düzenler.\n\n3. HİZMET VE BEDEL\nAbonelik planı ve bedeli sipariş özetinde belirtilir; KDV dahildir. Ödeme, iyzico altyapısı üzerinden güvenle alınır.\n\n4. CAYMA HAKKI\nDijital içerik/hizmetlerde mevzuatın öngördüğü koşullarda cayma hakkı kullanılabilir." + note, null);
            AddC("legal", 1, "gizlilik-politikasi", "Gizlilik ve Güvenlik Politikası",
                "Kişisel verilerin ve ödeme bilgilerinin korunmasına ilişkin politika.",
                "Liftonom olarak kullanıcı verilerinin gizliliğine önem veririz. Toplanan veriler yalnızca hizmetin sunulması amacıyla işlenir ve üçüncü taraflarla izinsiz paylaşılmaz.\n\nÖdeme işlemleri PCI-DSS uyumlu iyzico altyapısıyla yapılır; kart bilgileri sistemimizde saklanmaz. Veriler şifreli olarak saklanır ve düzenli yedeklenir." + note, null);
            AddC("legal", 2, "kvkk-aydinlatma-metni", "KVKK Aydınlatma Metni",
                "6698 sayılı Kanun kapsamında kişisel verilerin işlenmesine ilişkin aydınlatma.",
                "6698 sayılı Kişisel Verilerin Korunması Kanunu (KVKK) uyarınca, veri sorumlusu sıfatıyla kişisel verilerinizi hizmetin sunulması, faturalandırma ve yasal yükümlülükler amacıyla işleriz.\n\nKVKK madde 11 kapsamında; verilerinize erişme, düzeltilmesini/silinmesini isteme ve işlemeye itiraz etme haklarına sahipsiniz. Başvurularınızı [e-posta] adresine iletebilirsiniz." + note, null);
            AddC("legal", 3, "iptal-iade-kosullari", "İptal ve İade Koşulları",
                "Abonelik iptali ve iade süreçleri.",
                "Aylık aboneliklerde taahhüt bulunmaz; dilediğiniz zaman iptal edebilirsiniz. İptal, dönem sonunda geçerli olur ve sonraki dönem için ücret alınmaz.\n\nYıllık aboneliklerde iade talepleri, kullanılmamış dönem esas alınarak mevzuat çerçevesinde değerlendirilir. İptal ve iade talepleriniz için destek ekibimizle iletişime geçebilirsiniz." + note, null);
            AddC("legal", 4, "teslimat-ve-ifa", "Teslimat ve İfa Koşulları",
                "Dijital hizmetin ifa/teslim koşulları.",
                "Liftonom bir bulut (SaaS) hizmetidir; fiziksel teslimat yoktur. Ödemenin onaylanmasının ardından hesabınız anında aktifleşir ve hizmete erişim sağlanır.\n\nKurulum, veri aktarımı ve eğitim abonelik kapsamındadır. Hizmet kesintileri ve bakım pencereleri önceden bildirilir." + note, null);
            await db.SaveChangesAsync();
        }
    }

    if (!await db.PlatformAdmins.AnyAsync())
    {
        db.PlatformAdmins.Add(new Liftonom.Api.Models.PlatformAdmin
        {
            Name = "Süper Admin",
            Email = "admin@liftonom.com",
            Password = BCrypt.Net.BCrypt.HashPassword("admin123"),
            IsActive = true,
            CreatedAt = DateTime.UtcNow,
            UpdatedAt = DateTime.UtcNow,
        });
        await db.SaveChangesAsync();
    }
}

app.UseMiddleware<ExceptionMiddleware>();
app.UseCors();
app.UseAuthentication();
app.UseMiddleware<TenantMiddleware>(); // auth'tan SONRA: claim'ler hazır
app.UseAuthorization();
app.MapControllers();

app.Run();
