using System.Text;
using System.Text.Json;
using Liftonom.Api.Data;
using Liftonom.Api.Middleware;
using Liftonom.Api.Services;
using Microsoft.AspNetCore.Authentication.JwtBearer;
using Microsoft.EntityFrameworkCore;
using Microsoft.IdentityModel.Tokens;

QuestPDF.Settings.License = QuestPDF.Infrastructure.LicenseType.Community;

var builder = WebApplication.CreateBuilder(args);

// JSON: tüm anahtarlar snake_case (Laravel/frontend ile uyumlu)
builder.Services.AddControllers().AddJsonOptions(o =>
{
    o.JsonSerializerOptions.PropertyNamingPolicy = JsonNamingPolicy.SnakeCaseLower;
    o.JsonSerializerOptions.DictionaryKeyPolicy = JsonNamingPolicy.SnakeCaseLower;
});

// EF Core + PostgreSQL + snake_case (mevcut tablolara eşlenir)
builder.Services.AddDbContext<AppDbContext>(opt =>
    opt.UseNpgsql(builder.Configuration.GetConnectionString("Default"))
       .UseSnakeCaseNamingConvention());

// Servisler
builder.Services.AddScoped<ITenantContext, TenantContext>();
builder.Services.AddScoped<OtpService>();
builder.Services.AddScoped<TokenService>();
builder.Services.AddScoped<LedgerService>();
builder.Services.AddScoped<ScheduledJobs>();
builder.Services.AddScoped<PdfService>();
builder.Services.AddScoped<ISmsSender, LogSmsSender>();
builder.Services.AddScoped<FaultNotificationService>();
builder.Services.AddScoped<PushService>();
builder.Services.AddHttpClient();
// Ödeme: iyzico anahtarı varsa iyzico, yoksa mock
if (!string.IsNullOrEmpty(builder.Configuration["Iyzico:ApiKey"]))
    builder.Services.AddScoped<IPaymentGateway, IyzicoPaymentGateway>();
else
    builder.Services.AddScoped<IPaymentGateway, MockPaymentGateway>();
// WhatsApp: token varsa Meta Cloud API, yoksa log sürücüsü
if (!string.IsNullOrEmpty(builder.Configuration["WhatsApp:Token"]))
    builder.Services.AddScoped<IWhatsAppSender, MetaWhatsAppSender>();
else
    builder.Services.AddScoped<IWhatsAppSender, LogWhatsAppSender>();
builder.Services.AddHostedService<DailyJobsHostedService>();

// JWT
builder.Services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme)
    .AddJwtBearer(o =>
    {
        o.MapInboundClaims = false; // 'tid','uid' claim adlarını koru (URI'ye eşleme)
        o.TokenValidationParameters = new TokenValidationParameters
        {
            ValidateIssuer = true,
            ValidateAudience = true,
            ValidateLifetime = true,
            ValidateIssuerSigningKey = true,
            ValidIssuer = "Liftonom",
            ValidAudience = "Liftonom",
            IssuerSigningKey = new SymmetricSecurityKey(
                Encoding.UTF8.GetBytes(TokenService.JwtKey(builder.Configuration))),
        };
    });
builder.Services.AddAuthorizationBuilder()
    .AddPolicy("Admin", p => p.RequireClaim("scope", "admin"));

// CORS — geliştirmede tüm origin'lere izin (Next.js farklı port)
builder.Services.AddCors(o => o.AddDefaultPolicy(p =>
    p.AllowAnyOrigin().AllowAnyHeader().AllowAnyMethod()));

var app = builder.Build();

// Veritabanı hazırlığı + varsayılan süper admin (idempotent).
// Taze/boş DB'de EF modeli tam şema kaynağıdır → EnsureCreated tüm tabloları kurar
// (tablolar zaten varsa hiçbir şey yapmaz). RAW SQL migration'lar yalnız eski DB'yi evriltir.
using (var scope = app.Services.CreateScope())
{
    var db = scope.ServiceProvider.GetRequiredService<Liftonom.Api.Data.AppDbContext>();
    var startupLog = scope.ServiceProvider.GetRequiredService<ILoggerFactory>().CreateLogger("Startup");

    // Postgres konteyneri API'den sonra hazır olabilir — kısa yeniden deneme döngüsü.
    for (var attempt = 1; ; attempt++)
    {
        try { await db.Database.EnsureCreatedAsync(); break; }
        catch (Exception ex) when (attempt < 12)
        {
            startupLog.LogWarning("DB hazır değil (deneme {Attempt}/12): {Message}", attempt, ex.Message);
            await Task.Delay(TimeSpan.FromSeconds(3));
        }
    }

    // Süper Admin ek tabloları — mevcut DB'de EnsureCreated eklemez, idempotent oluştur.
    await db.Database.ExecuteSqlRawAsync("""
        CREATE TABLE IF NOT EXISTS subscription_contracts (
          id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          tenant_id bigint NOT NULL,
          title text NOT NULL DEFAULT '',
          plan text,
          amount numeric(18,2) NOT NULL DEFAULT 0,
          currency text NOT NULL DEFAULT 'TRY',
          start_date date,
          end_date date,
          status text NOT NULL DEFAULT 'active',
          notes text,
          created_at timestamptz NOT NULL DEFAULT now(),
          updated_at timestamptz NOT NULL DEFAULT now(),
          deleted_at timestamptz
        );
        CREATE INDEX IF NOT EXISTS ix_subscription_contracts_tenant ON subscription_contracts (tenant_id);
        CREATE TABLE IF NOT EXISTS platform_settings (
          id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          platform_name text,
          support_email text,
          default_plan text,
          created_at timestamptz NOT NULL DEFAULT now(),
          updated_at timestamptz NOT NULL DEFAULT now()
        );
        CREATE TABLE IF NOT EXISTS landing_items (
          id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          section text NOT NULL DEFAULT 'feature',
          title text NOT NULL DEFAULT '',
          description text,
          icon text,
          sort_order int NOT NULL DEFAULT 0,
          is_active boolean NOT NULL DEFAULT true,
          created_at timestamptz NOT NULL DEFAULT now(),
          updated_at timestamptz NOT NULL DEFAULT now()
        );
        CREATE TABLE IF NOT EXISTS landing_settings (
          id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          hero_badge text,
          hero_title text,
          hero_title_accent text,
          hero_subtitle text,
          show_pricing boolean NOT NULL DEFAULT true,
          created_at timestamptz NOT NULL DEFAULT now(),
          updated_at timestamptz NOT NULL DEFAULT now()
        );
        """);

    if (!await db.PlatformSettings.AnyAsync())
    {
        db.PlatformSettings.Add(new Liftonom.Api.Models.PlatformSetting
        {
            PlatformName = "Liftonom", SupportEmail = "info@liftonom.com", DefaultPlan = "trial",
            CreatedAt = DateTime.UtcNow, UpdatedAt = DateTime.UtcNow,
        });
        await db.SaveChangesAsync();
    }

    // Landing içeriği (tanıtım sayfası) — varsayılan içerik, süper adminden düzenlenir.
    if (!await db.LandingSettings.AnyAsync())
    {
        db.LandingSettings.Add(new Liftonom.Api.Models.LandingSetting
        {
            HeroBadge = "Asansör bakım & servis yönetim platformu",
            HeroTitle = "Asansör operasyonunuzu",
            HeroTitleAccent = "tek panelden",
            HeroSubtitle = "Bakım, arıza, muayene, stok, finans ve saha ekibi — hepsi Liftonom'da. Ofis paneli ve teknisyen mobil uygulamasıyla sahayı gerçek zamanlı takip edin.",
            ShowPricing = true, CreatedAt = DateTime.UtcNow, UpdatedAt = DateTime.UtcNow,
        });
        await db.SaveChangesAsync();
    }
    if (!await db.LandingItems.AnyAsync())
    {
        var lnow = DateTime.UtcNow;
        var order = 0;
        void Add(string section, string title, string? desc, string? icon)
            => db.LandingItems.Add(new Liftonom.Api.Models.LandingItem
            {
                Section = section, Title = title, Description = desc, Icon = icon,
                SortOrder = order++, IsActive = true, CreatedAt = lnow, UpdatedAt = lnow,
            });

        order = 0;
        Add("feature", "Akıllı Bakım Takvimi", "Periyodik bakımlar otomatik planlanır; 30/15/7/1 gün önce hatırlatma. Hiçbir bakım atlanmaz.", "CalendarClock");
        Add("feature", "6 Aşamalı Arıza Yönetimi", "Bildirim → sevk → inceleme → onarım → parça → tamamlandı. Her aşama zaman damgalı, teknisyen konumuyla.", "Wrench");
        Add("feature", "Offline Mobil Çalışma", "Makine dairesi, sinyalsiz bölge — internet olmadan bakım tamamlanır, bağlantı gelince senkronlanır.", "WifiOff");
        Add("feature", "QR ile Sıfır Temaslı Arıza", "Müşteri kabindeki QR'ı okutur, uygulama indirmeden arıza bildirir; size anında bildirim düşer.", "QrCode");
        Add("feature", "TSE A/B/C/D Dijital Form", "Mevzuata uygun periyodik kontrol formları mobilde doldurulur, müşteri imzalar, bulutta arşivlenir.", "ShieldCheck");
        Add("feature", "Sahada Mobil Tahsilat", "Teknisyen nakit/kart/online link ile anında tahsilat alır; dijital makbuz oluşur.", "Wallet");

        order = 0;
        Add("module", "Bakım Takip", "Periyodik bakımları planla, ata; dijital servis formu + fotoğraf + imzayla raporla.", "CalendarClock");
        Add("module", "Arıza Yönetimi", "Arızalar tek panele düşer, en yakın teknisyene atanır, SLA ölçülür.", "Wrench");
        Add("module", "Teknisyen Mobil", "iOS + Android native uygulama. Sahada görev al, tamamla, offline çalış.", "Smartphone");
        Add("module", "Fatura & Tahsilat", "Bakım kapanışında tek tıkla fatura; online ödeme linki ve vade takibi.", "Receipt");
        Add("module", "Stok & Depo", "Ürün, kategori, lokasyon, tedarikçi + düşük stok uyarıları.", "Boxes");
        Add("module", "Müşteri Portalı", "Bina yöneticisi binalarını, bakımlarını ve arızalarını görür.", "Users");

        order = 0;
        Add("step", "60 Saniyede Kayıt", "E-posta ile firmanı oluştur; hesabın anında aktif. Kredi kartı gerekmez.", "UserPlus");
        Add("step", "Verilerini Aktar", "Mevcut Excel verilerini toplu yükle. Ekibimiz transfer desteği sunar.", "Upload");
        Add("step", "Ekibini Davet Et", "Teknisyen, ofis, finans — herkesi rolüne göre ekle. Saha hazır.", "Users");
        Add("step", "Dijital Operasyona Geç", "Bakım, arıza, fatura, sözleşme tek panelde. Şeffaflık müşteri portalıyla.", "Rocket");

        order = 0;
        Add("compare_old", "Periyodik bakım takvimi unutulur, ceza riski doğar", null, null);
        Add("compare_old", "Teknisyen sahada ne yaptı akşama kadar belirsiz", null, null);
        Add("compare_old", "Servis formları kağıtta; denetimde belge bulunamaz", null, null);
        Add("compare_old", "Fatura kesimi sarkar, tahsilat geç kalır", null, null);
        Add("compare_old", "Müşteri 'bakım ne zamandı?' diye sürekli arar", null, null);

        order = 0;
        Add("compare_new", "Bakım takvimi otomatik; 30/15/7/1 gün önce hatırlatma", null, null);
        Add("compare_new", "Saha durumu canlı; konum, fotoğraf ve imza anında ofiste", null, null);
        Add("compare_new", "Dijital form bulutta; denetimde 30 saniyede belge", null, null);
        Add("compare_new", "Bakım kapanırken tek tıkla fatura + online ödeme linki", null, null);
        Add("compare_new", "Müşteri portalı + QR ile bilgi müşterinin elinde", null, null);

        await db.SaveChangesAsync();
    }

    // Varsayılan planlar (landing fiyatlandırma + admin Planlar modülü için)
    if (!await db.Plans.AnyAsync())
    {
        var pnow = DateTime.UtcNow;
        db.Plans.AddRange(
            new Liftonom.Api.Models.Plan { Code = "baslangic", Name = "Başlangıç", MonthlyPrice = 1500m, MaxUsers = 10, MaxElevators = 500, IsActive = true, CreatedAt = pnow, UpdatedAt = pnow },
            new Liftonom.Api.Models.Plan { Code = "pro", Name = "Professional", MonthlyPrice = 2500m, MaxUsers = 25, MaxElevators = 1000, IsActive = true, CreatedAt = pnow, UpdatedAt = pnow },
            new Liftonom.Api.Models.Plan { Code = "kurumsal", Name = "Kurumsal", MonthlyPrice = 3500m, MaxUsers = null, MaxElevators = 2000, IsActive = true, CreatedAt = pnow, UpdatedAt = pnow }
        );
        await db.SaveChangesAsync();
    }

    if (!await db.PlatformAdmins.AnyAsync())
    {
        db.PlatformAdmins.Add(new Liftonom.Api.Models.PlatformAdmin
        {
            Name = "Süper Admin",
            Email = "admin@liftonom.com",
            Password = BCrypt.Net.BCrypt.HashPassword("admin123"),
            IsActive = true,
            CreatedAt = DateTime.UtcNow,
            UpdatedAt = DateTime.UtcNow,
        });
        await db.SaveChangesAsync();
    }
}

app.UseMiddleware<ExceptionMiddleware>();
app.UseCors();
app.UseAuthentication();
app.UseMiddleware<TenantMiddleware>(); // auth'tan SONRA: claim'ler hazır
app.UseAuthorization();
app.MapControllers();

app.Run();
